- back-end/app/app.js
- back-end/app/public/login.html
login.html 파일 작성했고, app.js에 로그인 기능 구현 하였습니다.
> 로그인 기능 추가 및 임시 html 파일 작성했습니다.

- back-end/README.md
> 2/9 진행사항 업데이트

- ver_2/client/src/Login/LoginPage.jsx
- ver_2/server/routes/login.js
> 로그인 성공까지 코드 push

- back-end/create.sql
> 로그인 위한 create문 user 테이블 수정

- ver_2/client/src/Login/LoginPage.jsx
- ver_2/server/routes/login.js
front로 토큰 전달 확인
(html 웹브라우저 token 확인 완료)
> front로 토큰 전달 확인

- ver_2/server/routes/diary.js
- ver_2/server/server.js
diary.js 파일 중간 완성본입니다. (GET 메소드 사용)
1) 프론트 측에서 GET 방식으로 parameter 전달해주어야 함 (id, date)
2) js 파일에서 보내주는 res 값을 받아 화면에 띄워주어야 함
> diary.js 중간 완성 (프론트랑 연결 필요)

- ver_2/client/src/Home/HomePage.jsx
- ver_2/server/routes/diary.js
- ver_2/server/server.js
HomePage.jsx에서 POST로 전달해준 id와 date값을 받아
해당하는 diary console창 출력까지 성공
> diary.js sql문 실행

- ver_2/server/routes/diary.js
diary.js 파일 완성했습니다.
front쪽으로 json형태의 diary 정보 전달 가능합니다.
pull 잊어버리고 계속 local commit을 선행해서 또 merge branch 됐습니다.. 죄송합니당..
아마 문제는 없을 것 같아요..!
> diary.js 완성

- ver_2/server/routes/diary_delete.js
- ver_2/server/server.js
diary_delete.js 파일 완료 및 api 추가(server.js)
> diary_delete.js 파일 완료 및 api 추가(server.js)

- ver_2/server/server.js
> server.js 수정 (정상작동)

- ver_2/server/routes/write.js
> write.js res 보내기

- ver_2/client/src/Write/WritePage.jsx
- ver_2/server/routes/home.js
- ver_2/server/server.js
로컬 스토리지에서 토큰을 2번 getItem을 통해서 받아올 시 undefined 되는 오류 수정 필요
> fix: 홈페이지 오류 수정 1차 코드

- ver_past/back-end/create.sql
> create문 수정

- ver_2/server/routes/diary.js
diary.js site_title 넘겨주기 수정 완료
> diary.js site_title 넘겨주기 수정 완료

- ver_2/server/routes/myPage.js
res에 추가된 점
ex) attendance_rate: 15
> myPage 월 별 출석률 기능 추가

- ver_2/server/routes/myPage.js
> 이달의 플리 기능 완성

- ver_2/server/routes/myPage.js
mypage 오류 수정
unexpected token 오류 수정
> mypage 오류 수정

- ver_2/server/routes/myPage.js
> mypage.js 1위 플리 썸네일 res

- ver_2/server/routes/diary.js
> diary.js 로딩 중 오류 수정

- ver_2/server/routes/myPage.js
> myPage.js 기능 구현 완료

- ver_2/client/src/Login/LoginPage.jsx
- ver_2/server/routes/login.js
> 토큰 시간 일주일로 하였고, 로컬스토리지에서 세션스토리지로 변경하였습니다.

- ver_2/server/routes/diary.js
- ver_2/server/routes/myPage.js
> diary.js 카테고리 5개 맞춤형 제공

- ver_2/server/routes/myPage.js
mypage.js 월별 카테고리 순위 쿼리문 수정
select n.count, k.category from keyword as k join (select diary_keyword, count(diary_keyword) as count from diary where diary_writer_id = "hello" and diary_write_date like "2023-02-__" and diary_keyword is not null group by diary_keyword order by count(diary_keyword) desc) as n ON k.keyword = n.diary_keyword group by n.diary_keyword order by n.count desc limit 5;
> mypage.js 월별 카테고리 순위 쿼리문 수정

- ver_2/server/routes/myPage.js
[myPage.js 쿼리 결과 길이 0일 경우 오류 수정](https://github.com/Moon-seok-ho/sw_team_pj/commit/9bc29bc1cdabc0e4bbf155e9012edf1218c326e6)
> myPage.js 쿼리 결과 길이 0일 경우 오류 수정

- ver_2/client/src/Edit/EditPage.jsx
- ver_2/client/src/Mypage/Mypage.jsx
> mypage.jsx 데이터 0일때 플리이미지 뜨게 안하는것, edit.jsx 세션스토리지로 모두 변경하였습니다.

- ver_2/server/routes/login.js
login.js 경우에 따라 상태 code 전달 구분
res에 json 넣어서 send
json 내부 ex) "code" : 400
상태 코드 정리
+) id, pw 공란의 경우엔 front에서 처리 필요 (backend 호출 전에 예외처리해야 함)
1) 404: db 연결 실패 OR sql문 실행 실패 (시스템적 오류)
3) 401: DB에 없는 id인 경우 (id 불일치)
4) 402: id는 맞지만, pw가 틀린 경우 (pw 불일치)
5) 200: 모두 정상 작동
> login.js 경우에 따라 상태 code 전달 구분

- ver_2/client/src/Login/LoginPage.jsx
> LoginPage.jsx 로그인 alert문을 서버응답에 따라 변경

- ver_2/server/routes/login.js
> login.js status 주석처리입니다.

- ver_2/server/routes/myPage.js
myPage.js 키워드 기능 쿼리문 수정
"select category, sum(count) as count from (select * from keyword as k join (select diary_keyword, count(diary_keyword) as count from diary where diary_writer_id = ? and diary_write_date like ? and diary_keyword is not null group by diary_keyword) as n ON k.keyword = n.diary_keyword group by k.keyword) as a group by category order by count desc limit 5;",
> myPage.js 키워드 기능 쿼리문 수정

- ver_2/server/routes/diary_delete.js
- ver_2/server/routes/write.js
diary_delete.js dataList, summaryList 전달하도록 수정
& write.js res.end() 코드 추가
> diary_delete.js dataList, summaryList 전달하도록 수정

- ver_2/server/routes/diary_delete.js
> diary_delete.js 정상동작 확인완료
